SaidIt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("main.urls")),
]

accounts/urls.py
from . import views
from django.urls import path
from .views import (
    LoginView,
    LogoutView,
    AccountsListView,
    # AccountCreateView,
    AccountDetailView,
    AccountUpdateView,
    AccountDeleteView,
    RegisterView,
)

app_name = "account"

urlpatterns = [
    path("login", LoginView.as_view(), name="Login"),
    path("logout", LogoutView.as_view(), name="Logout"),
    path("register", RegisterView.as_view(), name="Register"),
    path("", AccountsListView.as_view(), name="Accounts"),
    # path("new", AccountCreateView.as_view(), name="NewAccount"),
    path("new1", views.accountCreateView, name="newAccount1"),
    path("<str:pk>/details", AccountDetailView.as_view(), name="AccountDetails"),
    path("<str:pk>/update", AccountUpdateView.as_view(), name="AccountUpdate"),
    path("<str:pk>/delete", AccountDeleteView.as_view(), name="DeleteAccount"),
]

main/urls.py
from django.urls import path
from .views import (
    LandingPageView,
)

app_name = "accounts"

urlpatterns = [
    path("", LandingPageView.as_view(), name="LandingPage"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime


# Create your models here.
class Job_Title(models.Model):
    title = models.CharField(max_length=48)

    def __str__(self) -> str:
        return self.title


class Interest(models.Model):
    name = models.CharField(max_length=48)

    def __str__(self) -> str:
        return self.name


class Employment_History(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="emploment_history"
    )
    company = models.CharField(max_length=48)
    position = models.ForeignKey(
        Job_Title, on_delete=models.CASCADE, blank=True, null=True
    )
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self) -> str:
        return f"{self.position} @ {self.company}"


class User_Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="user_profile"
    )
    first_name = models.CharField(max_length=48, blank=True, null=True)
    surname = models.CharField(max_length=48, blank=True, null=True)
    email = models.CharField(max_length=48, blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True, default="")
    date_of_birth = models.DateTimeField(
        blank=True, null=True, default=timezone.make_aware(datetime(2000, 1, 1))
    )
    title = models.CharField(max_length=5, blank=True, null=True, default="")
    interests = models.ManyToManyField("Interest", blank=True)

    def __str__(self) -> str:
        return f"{self.first_name} {self.surname}"

accounts/forms.py
# Models
from django.contrib.auth.models import User
from .models import User_Profile, Employment_History

# Forms
from django.contrib.auth.forms import UserCreationForm
from django import forms

# Crispy forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class meta:
        model = User
        fields = ["username", "password1", "password2"]


class UserAccountForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

    def __ini__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_class = "form-horizontal"
        self.helper.add_input(Submit("submit", "Submit"))


class UserProfileForm(forms.ModelForm):
    first_name = forms.CharField(required=True)
    # surname = forms.CharField(required=True)
    # email = forms.EmailField()

    class Meta:
        model = User_Profile
        fields = (
            # "title",
            "first_name",
            # "surname",
            # "date_of_birth",
            # "email",
            # "phone_number",
            # "interests",
        )
        # widgets = {
        #     "date_of_birth": forms.DateInput(attrs={"type": "date"}),
        #     "interests": forms.SelectMultiple(
        #         attrs={
        #             "class": "form-select select2 interests-multiple",
        #             "placeholder": "Select Interests",
        #             "id": "InterestsSelect",
        #         }
        #     ),
        # }

    def __ini__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_class = "form-horizontal"
        self.helper.add_input(Submit("submit", "Submit"))


class EmploymentHistoryForm(forms.ModelForm):
    class Meta:
        model = Employment_History
        fields = ("company", "position", "start_date", "end_date")
        widgets = {
            "start_date": forms.DateInput(attrs={"type": "date"}),
            "end_date": forms.DateInput(attrs={"type": "date"}),
            "position": forms.SelectMultiple(
                attrs={
                    "class": "form-select select2 postion-multiple",
                    "placeholder": "Select postion",
                    "id": "PostionSelect",
                }
            ),
        }

    def __ini__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_class = "form-horizontal"
        self.helper.add_input(Submit("submit", "Submit"))

accounts/views.py
import http
from sys import prefix
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.forms import formset_factory

# Transaction
from django.db import transaction

# Generic Views
from django.views.generic import (
    View,
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
)

# Forms
from .forms import UserAccountForm, UserProfileForm, EmploymentHistoryForm

# Models
from django.contrib.auth.models import User
from .models import Employment_History, User_Profile

# Create your views here.


class LoginView(View):
    template_name = "/.html"


class LogoutView(View):
    template_name = "/.html"


class RegisterView(View):
    template_name = "/.html"


class AccountsListView(ListView):
    model = User
    template_name = "accounts/accountsListPage.html"


def accountCreateView(request):
    template_name = "accounts/accountCreatePage.html"
    EmploymentHistoryFormSet = formset_factory(EmploymentHistoryForm, extra=1)
    
    if request.method == "POST":
        user_form = UserAccountForm(request.POST, prefix="user_form")
        profile_form = UserProfileForm(request.POST, prefix="profile_form")
        employment_history_formset = EmploymentHistoryForm(request.POST, prefix="employment_history_formset")
        print(request.POST)
        
        if (user_form.is_valid() and profile_form.is_valid()):
            # Save user
            user_form.save()
            print("User saved!")
            # Create new profile instance, but dont save yet. First need to set the user
            profile_form.save(commit=False)
            print("Profile created")
            # Set the user for the profile
            profile_form.user.id = user_form.id
            print("profile updated with user")
            # save new profile instance
            profile_form.save()
            print("profile saved saved!")
            return HttpResponse("User and profile have been created and saved")



        return HttpResponse(request.POST)

    EmploymentHistoryFormSet = formset_factory(EmploymentHistoryForm, extra=1)
    employment_history_formset = EmploymentHistoryFormSet()
    user_form = UserAccountForm(prefix="user_form")
    profile_form = UserProfileForm(prefix="profile_form")
    employment_history_form = EmploymentHistoryForm()
    context = {
        "form": user_form,
        "profile_form": profile_form,
        "employment_history_formset": employment_history_formset,
    }

    return render(request, template_name, context)


class AccountCreateView(CreateView):
    template_name = "accounts/accountCreatePage.html"
    # model = User
    form_class = UserAccountForm
    success_url = reverse_lazy("account:Accounts")

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.get_context_data())

    def form_valid(self, form):
        context = self.get_context_data()
        with transaction.atomic():
            # create new user
            print("new user")
        # save the user
        # # this will send a signal to create a profile
        # update profile with details from profile form
        # create new emp hist objects from form? iterate through form set, create new empHist

        # context = self.get_context_data()
        # user_profile_form = context["profile_form"]
        # user_profile_form = context["employment_history_form"]
        # # Use Django's transaction.atomic to ensure the atomicity of the operation
        # with transaction.atomic():
        #     response = super().form_valid(form)  # This will create the User

        #     # You can now access self.object to get the newly created User instance
        #     user = self.object

        #     # Creating the UserProfile
        #     profile_form_instance = UserProfileForm(self.request.POST)
        #     if profile_form_instance.is_valid():
        #         user_profile = profile_form_instance.save(commit=False)
        #         user_profile.user = user  # Set the foreign key to the new user
        #         user_profile.save()
        #     else:
        #         form.add_error(None, "User Profile data is invalid")
        #         return self.form_invalid(form)

        #     # Creating the EmploymentHistory
        #     employment_history_form_instance = EmploymentHistoryForm(self.request.POST)
        #     if employment_history_form_instance.is_valid():
        #         employment_history = employment_history_form_instance.save(commit=False)
        #         employment_history.user = user  # Set the foreign key to the new user
        #         employment_history.save()
        #     else:
        #         form.add_error(None, "Employment History data is invalid")
        #         return self.form_invalid(form)

        #     # Return the original response if all related objects are created successfully
        #     return response

    def get_context_data(self, **kwargs):
        # Add UserProfileForm and EmploymentHistoryForm to the context
        context = super().get_context_data(self, **kwargs)
        if self.request.POST:
            context["form"] = UserAccountForm(self.request.POST)
            context["profile_form"] = UserProfileForm(self.request.POST)
            context["employment_history_form"] = EmploymentHistoryForm(
                self.request.POST
            )
        else:
            context["form"] = UserAccountForm()
            context["profile_form"] = UserProfileForm()
            context["employment_history_form"] = EmploymentHistoryForm()
        return context


class AccountDetailView(DetailView):
    template_name = "accounts/accountDetailsPage.html"
    model = User


class AccountUpdateView(UpdateView):
    template_name = "accounts/accountUpdatePage.html"
    model = User


class AccountDeleteView(DeleteView):
    model = User
    success_url = reverse_lazy("account:Accounts")
    template_name = "accounts/user_confirm_delete.html"

accounts/templates/accounts/accountCreatePage.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<section class="container">
    {% for hidden_field in form.hidden_fields %}
      {{ hidden_field.errors }}
      {{ hidden_field }}
    {% endfor %}


    <h2>Create New Account</h2>
    <form method="POST" id="newAccountForm" action="{% url 'account:newAccount1' %}" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="card mb-3">
          <div class="card-header">
             New User
          </div>
          <div class="card-body">
                  <div class="row">
                      
                      {% crispy form %}
                  </div>
        </div>
      </div>
      <div class="card mb-3">
        <div class="card-header">
           Profile Details 
        </div>
        <div class="card-body">
                <div class="row">
                    {% crispy profile_form %}
                </div>
      </div>
    </div>
    {{ formset.management_form }}
    {% for frm in employment_history_formset %}
    <div class="card mb-3">
      <div class="card-header">
         Employment History
      </div>
      <div class="card-body">
        <div class="row">
          {{ frm|crispy }}
        </div>
      </div>
    </div>
    {% endfor %}
  <button type="submit" form="newAccountForm" class="btn btn-primary">Add New User</button>
    </form>
</section>

{% endblock content %}

accounts/templates/accounts/accountDetailsPage.html
{% extends "main/base.html" %}

{% block content %}

<section class="container-md">
    <!-- Left Panel -->
    <div class="row gutters-sm">
        <div class="col-md-4 mb-3">
            <!-- User Card -->
          <div class="card">
            <div class="card-body">
              <div class="d-flex flex-column align-items-center text-center">
                <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                <div class="mt-3">
                  <h4>{{ user_profile.user.username }}</h4>
                  <p class="text-secondary mb-1">{{ user_profile.first_name }} {{ user_profile.surname }}</p>
                  <p class="text-muted font-size-sm">{{ user_profile.email }}</p>
                  <a href="#" class="btn btn-outline-primary">Posts</a>
                </div>
              </div>
            </div>
          </div>
          <!-- Profile Details Card -->

        </div>
        <div class="col-md-8">
            <!-- User Info Card -->
          <div class="card mb-3">
            <div class="card-header">
                Profile Details
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0">First Name</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                  {{ user_profile.first_name }}
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0">Surname</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                  {{ user_profile.surname }}
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0">Email</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                    {{ user_profile.email }}
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0">Phone</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                    {{ user_profile.phone_number }}
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0">Interests</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                    {{ user_profile.interests }}
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-12">
                  <a class="btn btn-outline-warning " href="#">Edit</a>
                </div>
              </div>
            </div>
          </div>

          {% for employment in user.employment_history.all %}
          <!-- User Employment History Card -->
          <div class="card mb-3">
              <div class="card-header">
                  Employment History
              </div>
           <div class="card-body">
             <div class="row">
               <div class="col-sm-3">
                 <h6 class="mb-0">Company Name</h6>
               </div>
               <div class="col-sm-9 text-secondary">
                {{ employment.organisation_name }}
               </div>
             </div>
             <hr>
             <div class="row">
               <div class="col-sm-3">
                 <h6 class="mb-0">Position</h6>
               </div>
               <div class="col-sm-9 text-secondary">
                 {{ employment.position }}
               </div>
             </div>
             <hr>
             <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0">Start Date</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                  {{ employment.start_date|date }}
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <h6 class="mb-0">End Date</h6>
                </div>
                <div class="col-sm-9 text-secondary">
                  {{ employment.end_date|date }}
                </div>
              </div>
              <hr>
             <div class="row">
               <div class="col-sm-12">
                 <a class="btn btn-outline-warning" target="__blank" href="#">Edit</a>
                 <a class="btn btn-outline-danger " target="__blank" href="#">Delete</a>
               </div>
             </div>
           </div>
         </div>
          {% endfor %}
          <div class="mb-4 w-75 btn-group">
            <a href="" class=" btn btn-primary">Add Employment</a>
            <a href="" class=" btn btn-danger">Delete Account</a>
          </div>
        </div>
      </div>
</section>

{% endblock %}

accounts/templates/accounts/accountsListPage.html
{% extends 'main/base.html' %}

{% block content %}
<section class="container-lg  mb-4">
    <ul class="col list-group ">
        <div class=" row  my-4 ">
            <a class=" w-25 mx-auto btn btn-lg btn-primary text-decoration-none" href="{% url 'account:newAccount1' %}" style="min-width: 18rem;"> New Account</a>
        </div>
        {% for usr in user_list %}
            <div class="mx-auto text-decoration-none card text-dark bg-light mb-3" style="width: 18rem;">
                <div class="card">
                    <div class="d-flex flex-row justify-content-between card-header">
                        <h5 class="">{{ usr.username|title }}</h5>
                        <div class="">
                            <div style="font-size: 0.75em;">
                                User ID:{{ usr.pk }}
                            </div>
                            <div style="font-size: 0.75em;">
                                Profile ID:{{ usr.user_profile.pk }}
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{% if usr.user_profile.title %}{{ usr.user_profile.title }} {% endif %}{{ usr.user_profile.first_name|title }} {{ usr.user_profile.surname|title }}</h5>
                        <p class="card-text">Posts: {{ usr.posts.all|length }}</p>
                        <div class="btn-group">
                            <a href="{% url 'account:AccountDetails'  pk=usr.pk  %}" class="btn btn-info">View</a>
                            <a href="{% url 'account:DeleteAccount' pk=usr.pk  %}" class="btn btn-danger">Delete</a>
                        </div>
                    </div> 
                </div>
            </div>
        {% endfor %}
    </ul>
</section>
{% endblock %}

accounts/templates/accounts/user_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
<form method="post">{% csrf_token %}
	



    <p>Are you sure you want to delete "{{ object }}"?</p>
    
    
    
    
        <input type="submit" value="Confirm">
    </form>
    
{% endblock %}