SaidIt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("main.urls")),
]

accounts/urls.py
from . import views
from django.urls import path
from .views import (
    LoginView,
    LogoutView,
    AccountsListView,
    # AccountCreateView,
    AccountDetailView,
    AccountUpdateView,
    AccountDeleteView,
    RegisterView,
)

app_name = "account"

urlpatterns = [
    path("login", LoginView.as_view(), name="Login"),
    path("logout", LogoutView.as_view(), name="Logout"),
    path("register", RegisterView.as_view(), name="Register"),
    path("", AccountsListView.as_view(), name="Accounts"),
    # path("new", AccountCreateView.as_view(), name="NewAccount"),
    path("new1", views.accountCreateView, name="newAccount1"),
    path("<str:pk>/details", AccountDetailView.as_view(), name="AccountDetails"),
    path("<str:pk>/update", AccountUpdateView.as_view(), name="AccountUpdate"),
    path("<str:pk>/delete", AccountDeleteView.as_view(), name="DeleteAccount"),
]

main/urls.py
from django.urls import path
from .views import (
    LandingPageView,
)

app_name = "accounts"

urlpatterns = [
    path("", LandingPageView.as_view(), name="LandingPage"),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
# Generic Views
from django.views.generic import View
from django.shortcuts import render

# Create your views here.


class LandingPageView(View):
    template_name = "main/landingPage.html"

    def get(self, request):
        return render(request, self.template_name, {})

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static '/posts/style.css' %}">

    <!-- Select2 -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    

    <title>Y.com</title>
   
</head>
<body>
    {% include "main/navbar.html" %}
    
    <main id="main" class="mt-5"> 
      {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <div{% if message.tags %} role="alert" class="alert alert-success {{ message.tags }}"{% endif %}>
                <p>{{ message }}</p>
                <button type="button" class="btn-close justify-content-between" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        </ul>
      {% endif %}

    {% block content %}
    {% endblock %}
    </main>
</body>

<!-- <script src="{% static 'main/jquery/jquery-3.7.1.js' %}"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script>
  $(document).ready(function() {
    $('.interests-multiple').select2();
    $('#PositionSelect').select2();
    console.log("Hello, World!")
});
</script>
</html>

main/templates/main/landingPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Y.com</title>
    {% if messages %}
    {% for message in messages %}
   
    <script>
      alert("{{ message }}");
    </script>
   
    {% endfor %}
    {% endif %}
</head>
<body>
    <main class="container d-flex justify-content-center align-items-center vh-100">
        <div class="col">
            <div class="row container text-center m-4 header d-grid gap-2 d-sm-flex">
                <div class="col align-self-center">
                    <h1 class="">Y.com</h1>
                    <p class="">Let that sink in</p> 
                </div>
            </div>
            <div class="row d-grid gap-2 d-sm-flex justify-content-center">
                <a class="col btn btn-primary" href="{% url 'account:Login' %}">Log in</a>
                <a class="col btn btn-outline-secondary"  href="{% url 'account:Register' %}">Register</a>
            </div>  
        </div>
    </main>
    
</body>
</html>

main/templates/main/navbar.html
<header class="navbar navbar-expand-md navbar-dark bd-navbar bg-dark">
    <nav class="container-xxl flex-wrap flex-md-nowrap" aria-label="Main navigation">
      <a class="navbar-brand p-0 me-2" href="/" aria-label="Bootstrap">
        SaidIt
      </a>
  
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#bdNavbar" aria-controls="bdNavbar" aria-expanded="false" aria-label="Toggle navigation">
        menu
      </button>
  
      <div class="collapse navbar-collapse" id="bdNavbar">
        <ul class="navbar-nav flex-row flex-wrap bd-navbar-nav pt-2 py-md-0">
          <li class="nav-item col-6 col-md-auto">
            <a class="nav-link p-2" aria-current="page href="/" onclick="ga('send', 'event', 'Navbar', 'Community links', 'Bootstrap');">Home</a>
          </li>
        </ul>
  
        <hr class="d-md-none text-white-50">
  
        <ul class="navbar-nav flex-row flex-wrap ms-md-auto">
          <li class="nav-item col-6 col-md-auto">
            <a class="nav-link p-2" href="{% url 'account:AccountDetails' pk=user.pk %}" rel="noopener">
              {{ user|title }}
            </a>
          </li>
          <li class="nav-item col-6 col-md-auto">
            <a class="nav-link p-2" href="{% url 'account:Accounts' %}" >
              Accounts
            </a>
          </li>
          <li class="nav-item col-6 col-md-auto">
            <a class="nav-link p-2" href="#" >
              Logout
            </a>
          </li>
        </ul>
  
        <a class="btn btn-bd-download d-lg-inline-block my-2 my-md-0 ms-md-3" href="#">Download</a>
      </div>
    </nav>
  </header>

  <nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand">TwYtter</a>
      <h4>{{ title }}</h4>

      <div class="d-flex">
        <ul>
          <li>New Post</li>
          <li>{{user.username|title}}</li>
          <li>logout</li>
        </ul>
      </div>
      <!-- <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form> -->
    </div>
  </nav>